# Generated by Django 6.0.3 on 2026-03-28 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_description', models.TextField()),
                ('team_score', models.IntegerField(default=0, editable=False)),
                ('team_bonus_score', models.IntegerField(default=0)),
                ('team_members', models.ManyToManyField(related_name='participating_in_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
