# Generated by Django 6.0.3 on 2026-03-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_bonus_score',
        ),
    ]
