# Generated by Django 6.0.3 on 2026-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy88', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='points',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='mission',
            name='capture_type',
            field=models.CharField(choices=[('video', 'Video'), ('foto', 'Photo'), ('tekst', 'Text'), ('foto/video', 'Foto/Video')], default='foto/video', max_length=10),
        ),
    ]
