# Generated by Django 6.0.3 on 2026-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy88', '0002_mission_points_alter_mission_capture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='bonuspoints',
            field=models.IntegerField(default=0),
        ),
    ]
