# Generated by Django 6.0.3 on 2026-03-30 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy88', '0004_submission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['3gp', 'avi', 'bmp', 'flv', 'gif', 'heic', 'jpeg', 'jpg', 'm4v', 'mkv', 'mov', 'mp4', 'mpeg', 'mpg', 'ogv', 'png', 'svg', 'tif', 'tiff', 'ts', 'webm', 'webp'])]),
        ),
    ]
