# Generated by Django 6.0.3 on 2026-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazy88', '0005_alter_submission_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
